places = [{"placeName":"Kennedy Space Center","descrip":"Movie Apollo 13 was shot in part here during the 1990s. ","latitude":28.573469,"longitude":-80.65107},
    {"placeName":"Grande Oaks Gulf Club","descrip":"Golf scenes in Caddyshack were filmed at this location in Broward County.","latitude":26.0445,"longitude":-80.15307},
    {"placeName":"Crystal River","descrip":"Elvis Presley's Follow That Dream featured this scenic river.","latitude":28.9025,"longitude":-82.5926},
    {"placeName":"Wakulla Springs","descrip":"Iconic movie Creature From the Black Lagoon was filmed in part here.","latitude":30.2335,"longitude":-84.3052},
    {"placeName":"Fort Basinger","descrip":"Chain gang scenes in Cool Hand Luke were filmed in this rural Central Florida community.","latitude":27.3623,"longitude":-81.057},
    {"placeName":"The Vinnoy Park Hotel","descrip":"One of many St. Petersburg locations for Cocoon.","latitude":27.464124,"longitude":-82.374834},
    {"placeName":"Micanopy","descrip":"Just outside of Gainesville, this scenic location was used for Doc Hollywood.","latitude":29.5047,"longitude":-82.2798},
    {"placeName":"Brooksville","descrip":"This city was used in the filiming of horror movie, Deathdream.","latitude":28.5553,"longitude":-82.3879},
    {"placeName":"Clearwater Marine Aquarium ","descrip":"Dolphin Tale was filmed here based on the real events that occurred after a dolphin lost its tail at this aquarium.","latitude":27.9769,"longitude":-82.8177},
    {"placeName":"Magic Castle Inn & Suites","descrip":"The Florida Project used this location as the motel the main family stayed in.","latitude":28.3342714,"longitude":-81.4872815},
    {"placeName":"Liberty Sqaure Housing Project","descrip":"Moonlight features this Miami neighborhood as the hometown of the main character.","latitude":25.501,"longitude":-80.1312},
    {"placeName":"Boca Grande","descrip":"A small community located on Gasparilla Island, the film Out of Time shot here for the 2003 movie.","latitude":26.749,"longitude":-82.2617},
    {"placeName":"Billy's Stone Crab","descrip":"This location served as the fictional Scully's in Summer Rental.","latitude":27.675498,"longitude":-82.728556},
    {"placeName":"Amelia Island","descrip":"Sunshine State was largely filmed here. It played the fictional town of Delrona Beach.","latitude":30.6266,"longitude":-81.4609},
    {"placeName":"Bowman's Beach Helistop","descrip":"The helicopter stop on Bowman Beach was used in the opening scenes of Day of the Dead.","latitude":26.4592,"longitude":-82.1565},
    {"placeName":"Walt Disney World Resort","descrip":"The horror film Escape from Tomorrow was filmed here and the main location of the movie.","latitude":28.3772,"longitude":-81.5707},
    {"placeName":"Dunnellon ","descrip":"The church in the movie Jeepers Creepers was a real church in this town.","latitude":29.0491,"longitude":-82.4609},
    {"placeName":"Universal Studios","descrip":"A few casino scenes were filmed here in Ocean's Eleven.","latitude":28.4724,"longitude":-81.469},
    {"placeName":"Fontainebleau Miami Beach Resort","descrip":"The infamous pool scene in Scarface was filmed at this location.","latitude":25.8180847,"longitude":-80.1220423},
    {"placeName":"Modica Market","descrip":"One of the many locations used in The Truman Show. It can still be visited today. ","latitude":30.3200059,"longitude":-86.1369633}]